# -*- coding: utf-8 -*-
"""01. 데이터와 데이터분석.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11m2qwQNkJETAQtlf9ALUuS_m9apBkbuK

# matplotlib 선 그래프 그리기
"""

import matplotlib.pyplot as plt
plt.plot([1,2,3,4,5],[7,8,9,10,15])
plt.show()

x = [1,2,3,4,5]
y = [10,4,7,2,-1]
plt.plot(x,y)
plt.show()

plt.figure(figsize=(10,5))
plt.title("Graph", fontsize=20)
plt.xlabel("x data")
plt.ylabel("y label")

x = [1,2,3,4,5]
y = [10,4,7,2,-1]
plt.plot(x,y)
plt.show()

"""# 막대그래프 그리기"""

plt.bar(x,y)
plt.show()

"""# 박스플롯 그리기"""

import random
y = []
for a in range(19):
  y.append(random.randint(1,1000))
  
print(sorted(y))
plt.boxplot(y)
plt.show()

"""# csv파일 가져오기"""
import os
os.getcwd()

os.chdir("C:/Users/User/Documents/dev/이유찬/data_analysis/data/01.데이터와 데이터분석/")

import pandas as pd
path = 'cctv.csv'
cctv = pd.read_csv(path, encoding='cp949')

"""# 데이터 구성정보 알아보기"""

cctv.head()

"""# 데이터 전처리"""

cctv.info()

cctv.isna().sum()

cctv = cctv.fillna(0)
cctv.isna().sum()

cctv = cctv.dropna()
cctv.isna().sum()

# """# 한글 폰트 사용하기"""

# !sudo apt-get install -y fonts-nanum
# !sudo fc-cache -fv
# !rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
plt.rc('font', family = 'NanumBarunGothic')
plt.rc('axes', unicode_minus = False)

"""# CCTV 시각화 - 선그래프"""

plt.figure(figsize=(15,5))
plt.title('각 자치구별 CCTV 갯수', fontsize =10)

plt.plot(cctv['구분'], cctv['총계'])
plt.show()

"""# CCTV 시각화 - 막대그래프"""

plt.figure(figsize=(15,4))
plt.title("각 자치구별 쓰레기무단투기 CCTV 갯수", fontsize = 10)

plt.bar(cctv['구분'], cctv['쓰레기무단투기'])
plt.show()

"""# CCTV 시각화 - boxplot"""

plt.title("각 기관별 CCTV통계", fontsize = 10)
plt.grid(True)
plt.boxplot(cctv['총계'])
plt.show()

"""# 데이터의 평균값"""

import numpy as np
avg = np.mean(cctv['총계'])
avg

plt.title('각 기관별 CCTV 총계', fontsize = 15)
plt.hist(cctv['총계'], bins=20)
plt.show()